### ISSUE TITLE
Unsupported import of type: mem

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#137]
```sh
        throw new CompileError("Unsupported import of type: " + descrType);
        ^
Error: Unsupported import of type: mem
    at new CompileError (/home/xx/js-webassembly-interpreter/lib/errors.js:40:109)
    at parseImportSection (/home/x/js-webassembly-interpreter/lib/compiler/parsing/wasm/decoder.js:329:15)
    at parseSection (/home/xx/js-webassembly-interpreter/lib/compiler/parsing/wasm/decoder.js:889:18)
    at decode (/home/xx/js-webassembly-interpreter/lib/compiler/parsing/wasm/decoder.js:988:17)
    at Object.<anonymous> (/home/xx/js-webassembly-interpreter/lib/bin/wasmdump.js:20:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

wasm generated by Emscripten

**Comment by ColinEberhardt** [comment]
Ah, yes, when implementing store / load I tested exporting of memory, but not importing!
